docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Run Migrations
        command: /app/bin/rails db:migrate
        service: ruby
    - run:
        name: Print env
        command: env | sort
        service: ruby